version: '3.7'

services:

  api:
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log.ini
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/database
      - SECRET_KEY=secret_key_test
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - 5433:5432

volumes:
  postgres_data:
