import os

DATABASE_URL = os.getenv("DATABASE_URL")

# Auth
SECRET_KEY = os.getenv("SECRET_KEY")

# S3
BUCKET = os.getenv("BUCKET")
S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT_URL")
S3_REGION_NAME = os.getenv("S3_REGION_NAME")
S3_AWS_ACCESS_KEY_ID = os.getenv("S3_AWS_ACCESS_KEY_ID")
S3_AWS_SECRET_ACCESS_KEY = os.getenv("S3_AWS_SECRET_ACCESS_KEY")
